app:
  name: tower-go
  port: 10024

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: cesp001
  database: tower

redis:
  host: localhost
  port: 6379
  password: cesp@001
  db: 0
  enabled: true